name: Banker
main: me.fildon.Banker.banker
version: 1.0
author: fildon
commands:
    renter:
        description: This is the main command for the plugin.
        usage: /<command>
        aliases: [r]